[features]
seeds = false
[programs.localnet]
record_anchor = "HYTh8VkW6MeA1EUAjXeyrtAz6zHC8aAvaZd9Mn6dnwb4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/anurag/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
